name: Run WAT Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  Run-WAT-Tests:
    runs-on: ubuntu-latest
    container:
      image: docker://barichello/godot-ci:3.3.2
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Setup Python
        run: |
            apt update
            apt-get -y install python3.9 python3-requests
      - name: Install Packages
        run: ./package_manager/package_manager.py update
      - name: Run Tests
        run: godot addons/third_party/WAT/cli.tscn -run_all
