name: Run WAT Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  Run-WAT-Tests:
    runs-on: ubuntu-latest
    container:
      image: docker://barichello/godot-ci:3.3.2
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version:
            - '3.9.6'
            - 'requests'
          architecture: 'x64'
      - name: Install Packages
        run: ./package_manager/package_manager.py update
      - name: Run Tests
        run: godot addons/WAT/cli.tscn -run_all
