name: Run WAT Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  Run-WAT-Tests:
    runs-on: ubuntu-latest
    container:
      image: docker://barichello/godot-ci:3.3.2
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          submodules: true
      - name: Install Packages
        run: |
          apt update
          apt-get -y install python3.9
          python3.9 package_manager/package_manager.py
      - name: Run Tests
      - run: godot addons/WAT/cli.tscn -run_all
